mode = "dark"

accent = "#b36a54"
selection = "#1f211c"
muted = "#5c5e58"

background = "#060803"
dark_background = "#050602"
darker_background = "#030402"
lighter_background = "#1f211c"

foreground = "#FDEFBC"
dark_foreground = "#beb38d"
light_foreground = "#fdf1c6"
bright_foreground = "#fef3cd"

red = "#ba8c56"
yellow = "#ffee86"
orange = "#c49d6f"
green = "#d7c36c"
cyan = "#dde36f"
blue = "#b36a54"
magenta = "#e79661"
brown = "#765e43"

bright_red = "#d99e5a"
bright_yellow = "#ffec62"
bright_green = "#f3da63"
bright_cyan = "#f6fc66"
bright_blue = "#d4795e"
bright_magenta = "#ffa55e"
