mode = "dark"

accent = "#4b9265"
selection = "#201f2a"
muted = "#5e5d64"

background = "#070612"
dark_background = "#05050e"
darker_background = "#040309"
lighter_background = "#201f2a"

foreground = "#FAFAEA"
dark_foreground = "#bcbcb0"
light_foreground = "#fbfbed"
bright_foreground = "#fbfbef"

red = "#a89552"
yellow = "#f0fc93"
orange = "#b5a56c"
green = "#b7ce7c"
cyan = "#b0ef90"
blue = "#4b9265"
magenta = "#d6a24c"
brown = "#6d6341"

bright_red = "#c3aa54"
bright_yellow = "#f0fe76"
bright_green = "#cbe87a"
bright_cyan = "#bcff94"
bright_blue = "#51ab73"
bright_magenta = "#f8b43d"
