mode = "dark"

accent = "#3fa36b"
selection = "#1c1f1f"
muted = "#5c6f66"

background = "#0f1111"
dark_background = "#101212"
darker_background = "#0f1111"
lighter_background = "#131515"

foreground = "#d6e2dc"
dark_foreground = "#6F7B77"
light_foreground = "#5c6f66"
bright_foreground = "#f0fffa"

red = "#7a3e2b"
yellow = "#B08052"
orange = "#B08052"
green = "#3a6f73"
cyan = "#A6AC9F"
blue = "#5B7B5C"
magenta = "#5c6f66"
brown = "#5B7B5C"

bright_red = "#a35a3a"
bright_yellow = "#c2a070"
bright_green = "#4fd18f"
bright_cyan = "#8cf5c4"
bright_blue = "#4aa3a8"
bright_magenta = "#7a8f86"
