mode = "dark"

accent = "#3276ea"
selection = "#1a2123"
muted = "#565d5f"

background = "#00080b"
dark_background = "#000608"
darker_background = "#000406"
lighter_background = "#1a2123"

foreground = "#E9F9FC"
dark_foreground = "#afbbbd"
light_foreground = "#ecfafc"
bright_foreground = "#effbfd"

red = "#f8db78"
yellow = "#a8af4c"
orange = "#f9e08c"
green = "#508a29"
cyan = "#00a5a1"
blue = "#3276ea"
magenta = "#2381eb"
brown = "#958654"

bright_red = "#ffe92e"
bright_yellow = "#cbd64c"
bright_green = "#6db323"
bright_cyan = "#31cec8"
bright_blue = "#5496ff"
bright_magenta = "#48a2ff"
