mode = "dark"

accent = "#6C0000"
selection = "#32292C"
muted = "#8F7A94"

background = "#060606"
dark_background = "#141618"
darker_background = "#060606"
lighter_background = "#16191B"

foreground = "#EDEDED"
dark_foreground = "#7B848C"
light_foreground = "#8F7A94"
bright_foreground = "#F7F3EE"

red = "#C31D19"
yellow = "#5A5A5A"
orange = "#C89A56"
green = "#5A5A5A"
cyan = "#6C0000"
blue = "#6C0000"
magenta = "#6C0000"
brown = "#7F9A6F"

bright_red = "#6C0000"
bright_yellow = "#6C0000"
bright_green = "#6C0000"
bright_cyan = "#EDEDED"
bright_blue = "#6C0000"
bright_magenta = "#6C0000"
