mode = "dark"

accent = "#ad637d"
selection = "#1a1a1a"
muted = "#686163"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#1a1a1a"

foreground = "#ffa389"
dark_foreground = "#bf7a67"
light_foreground = "#ffb19b"
bright_foreground = "#ffbaa7"

red = "#c47d73"
yellow = "#ffd59e"
orange = "#cd9188"
green = "#f6ad77"
cyan = "#ffc766"
blue = "#ad637d"
magenta = "#ea8893"
brown = "#7b5752"

bright_red = "#e58d80"
bright_yellow = "#ffd08b"
bright_green = "#ffbe75"
bright_cyan = "#ffd95b"
bright_blue = "#cc7192"
bright_magenta = "#ff93a3"
