mode = "dark"

accent = "#5f81b8"
selection = "#1a2230"
muted = "#5c6066"

background = "#000919"
dark_background = "#000713"
darker_background = "#00050d"
lighter_background = "#1a2230"

foreground = "#808F9F"
dark_foreground = "#46505B"
light_foreground = "#A2BCD3"
bright_foreground = "#A7C3DD"

red = "#968dc6"
yellow = "#8affff"
orange = "#a69ecf"
green = "#75d0f7"
cyan = "#86e5ff"
blue = "#5f81b8"
magenta = "#98a6f3"
brown = "#645f7c"

bright_red = "#aca0e8"
bright_yellow = "#60ffff"
bright_green = "#6deaff"
bright_cyan = "#84feff"
bright_blue = "#6c96da"
bright_magenta = "#a8baff"
