mode = "dark"

accent = "#85a3d5"
selection = "#211d26"
muted = "#6b686e"

background = "#08040e"
dark_background = "#06030b"
darker_background = "#040207"
lighter_background = "#211d26"

foreground = "#F4EAAE"
dark_foreground = "#b7b083"
light_foreground = "#f6edba"
bright_foreground = "#f7efc2"

red = "#a76a5f"
yellow = "#cfb029"
orange = "#b48077"
green = "#f6e9ab"
cyan = "#b2ceff"
blue = "#85a3d5"
magenta = "#aa6b68"
brown = "#6c4d47"

bright_red = "#d28c7d"
bright_yellow = "#f0d000"
bright_green = "#ffee80"
bright_cyan = "#b3d9ff"
bright_blue = "#a8c8ff"
bright_magenta = "#d58d89"
