mode = "dark"

accent = "#c89a3d"
selection = "#314059"
muted = "#66616a"

background = "#191324"
dark_background = "#100b1a"
darker_background = "#0a0612"
lighter_background = "#2a2437"

foreground = "#ded7c6"
dark_foreground = "#7f7a6d"
light_foreground = "#f0ebdf"
bright_foreground = "#fbf8f0"

red = "#a96857"
yellow = "#cc9a62"
orange = "#ca9b65"
green = "#c89c68"
cyan = "#7ea0d2"
blue = "#7ca0d4"
magenta = "#775c8f"
brown = "#8c5848"

bright_red = "#cd7f6a"
bright_yellow = "#e9b371"
bright_green = "#ebb26d"
bright_cyan = "#93bbf8"
bright_blue = "#91bbfa"
bright_magenta = "#9474b2"
