mode = "dark"

accent = "#59B6C6"
selection = "#2A2233"
muted = "#8D6CCF"

background = "#14111B"
dark_background = "#13101A"
darker_background = "#14111B"
lighter_background = "#181520"

foreground = "#F3EAF6"
dark_foreground = "#8A7E93"
light_foreground = "#8D6CCF"
bright_foreground = "#FFF6FF"

red = "#9A5E5B"
yellow = "#F6B36B"
orange = "#F6B36B"
green = "#59B6C6"
cyan = "#f77689"
blue = "#8D6CCF"
magenta = "#6BD3DB"
brown = "#8EDFD3"

bright_red = "#FF8D9E"
bright_yellow = "#FFD98A"
bright_green = "#8EDFD3"
bright_cyan = "#90E1E1"
bright_blue = "#78D8FF"
bright_magenta = "#D75ACF"
