mode = "dark"

accent = "#3da9e3"
selection = "#2b1a1a"
muted = "#6f6866"

background = "#130100"
dark_background = "#0e0100"
darker_background = "#0a0100"
lighter_background = "#2b1a1a"

foreground = "#E9EBCC"
dark_foreground = "#afb099"
light_foreground = "#eceed4"
bright_foreground = "#eff0d9"

red = "#b65d4f"
yellow = "#989600"
orange = "#c17569"
green = "#d2c565"
cyan = "#71d4ff"
blue = "#3da9e3"
magenta = "#bb6158"
brown = "#74463f"

bright_red = "#e47e6b"
bright_yellow = "#bdbe00"
bright_green = "#e3d40b"
bright_cyan = "#4fe3ff"
bright_blue = "#5dcfff"
bright_magenta = "#e98276"
