mode = "dark"

accent = "#5a75d7"
selection = "#201c29"
muted = "#69676e"

background = "#070311"
dark_background = "#05020d"
darker_background = "#040209"
lighter_background = "#201c29"

foreground = "#FDE3A3"
dark_foreground = "#beaa7a"
light_foreground = "#fde7b1"
bright_foreground = "#feeaba"

red = "#e37562"
yellow = "#ffd46f"
orange = "#e78a7a"
green = "#ffc06e"
cyan = "#7285ff"
blue = "#5a75d7"
magenta = "#a560bd"
brown = "#8b5349"

bright_red = "#ff967d"
bright_yellow = "#ffe000"
bright_green = "#ffc931"
bright_cyan = "#96a4ff"
bright_blue = "#7c95ff"
bright_magenta = "#d07df3"
