mode = "dark"

accent = "#2b91ab"
selection = "#24282a"
muted = "#636a6e"

background = "#0C1012"
dark_background = "#090c0e"
darker_background = "#060809"
lighter_background = "#24282a"

foreground = "#71F1F1"
dark_foreground = "#55b5b5"
light_foreground = "#86f3f3"
bright_foreground = "#95f5f5"

red = "#67aa85"
yellow = "#88fff7"
orange = "#7eb797"
green = "#68ddd1"
cyan = "#4bf8ff"
blue = "#2b91ab"
magenta = "#5abbee"
brown = "#4c6e5b"

bright_red = "#6fc395"
bright_yellow = "#54fff5"
bright_green = "#53faeb"
bright_cyan = "#00ffff"
bright_blue = "#1fa9c9"
bright_magenta = "#4ed4ff"
